### ISSUE TITLE
Jede E-Mail landet im Spam Ordner bei AOL

### ISSUE THREAD

**Issue by simonschaufi** [tim3z/kaheim#24]
Hi,
jede E-Mail landet bei mir im Spam Ordner.

Hier ist der E-Mail header:

```
X-Apparently-To: xxx@aol.com; Sat, 10 Nov 2018 08:16:50 +0000
Return-Path: <no-reply@kaheim.de>
X-YahooFilteredBulk: 95.143.172.242
Received-SPF: none (domain of kaheim.de does not designate permitted sender hosts)
X-YMailISG: 1gEQQdoWLDs...
X-Originating-IP: [95.143.172.242]
Authentication-Results: mta4165.aol.mail.bf1.yahoo.com  from=kaheim.de; domainkeys=neutral (no sig);  from=kaheim.de; dkim=neutral (no sig)
Received: from 127.0.0.1  (EHLO aldebaran.uberspace.de) (95.143.172.242)
  by mta4165.aol.mail.bf1.yahoo.com with SMTPS; Sat, 10 Nov 2018 08:16:49 +0000
Received: (qmail 18324 invoked by uid 1220); 10 Nov 2018 08:16:45 -0000
Date: Sat, 10 Nov 2018 09:16:45 +0100
From: Kaheim <no-reply@kaheim.de>
To: xxx@aol.com
Message-ID: <5be693ed9b836_20922ad20687a5e8234ba@aldebaran.uberspace.de.mail>
Subject: [Kaheim] Neuer Eintrag auf Kaheim
Mime-Version: 1.0
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: quoted-printable
Content-Length: 461
```

Vielleicht solltet ihr lieber einen externen Dienst nutzen, um E-Mails zuzustellen zum Beispiel https://www.mailgun.com/ oder https://postmarkapp.com/ oder https://sendgrid.com/ oder https://mandrill.com/ oder https://de.sendinblue.com/

**Comment by matthias-g** [comment]
Danke für den Hinweis und die Vorschläge! Da müssen wir mal schauen, ob das bei anderen Providern auch so ist und ob wir etwas an unserem Setup verbessern können.
Einen externen Dienst würde ich dafür nur ungern nutzen, da wir die E-Mails an unsere Nutzer eigentlich nicht an dritte Parteien weitergeben wollen.

**Comment by matthias-g** [comment]
> Das Problem ist wohl, dass ihr die E-Mails über uberspace versendet aber die domain kaheim.de ist.

Kann gut sein, dass das mit reinspielt, aber verschiedene Domains im `From`-Header und beim SMTP-Server sind eigentlich nicht völlig unüblich. Bei einem externen Dienst wäre das ja wahrscheinlich auch der Fall.

**Comment by simonschaufi** [comment]
> Bei einem externen Dienst wäre das ja wahrscheinlich auch der Fall.

Korrekt, allerdings fügen die noch besondere Headerinformationen hinzu, die euch wohl fehlen.

**Comment by matthias-g** [comment]
Was wir noch machen könnten, wäre SPF und DKIM zu nutzen.
Ich kann allerdings nicht abschätzen, wie viel das wirklich bringt. Halte es auch für möglich, dass AOL da eine Art von Whitelisting benutzt, was bedeuten würde, dass wir wenig tun können, um etwas an dem Problem zu ändern.

**Comment by simonschaufi** [comment]
> Was wir noch machen könnten, wäre SPF und DKIM zu nutzen.

Das ist in der Tat eine gute Idee, wenn ihr darauf Zugriff habt und das konfigurieren könnt.

**Comment by lockejan** [comment]
> Was wir noch machen könnten, wäre SPF und DKIM zu nutzen.
> Ich kann allerdings nicht abschätzen, wie viel das wirklich bringt. Halte es auch für möglich, dass AOL da eine Art von Whitelisting benutzt, was bedeuten würde, dass wir wenig tun können, um etwas an dem Problem zu ändern.

Hab ähnliche Probleme mit outlook.com.
SPF ist ja mittlerweile schon im Einsatz.

Wäre toll, wenn DKIM auch noch käme.

**Comment by simonschaufi** [comment]
SPF dns records sind super einfach einzurichten, DKIM ist etwas komplizierter, da dann auch Emails signiert werden müssen. Wie ist hier der Stand?

**Comment by matthias-g** [comment]
SPF ist jetzt eingerichtet. DKIM scheint auch mit vertretbarem Aufwand möglich zu sein (https://github.com/jhawthorn/dkim).
In der nächsten Zeit steht der Umzug auf Uberspace 7 an. Um DKIM würde ich mich danach kümmern.

**Comment by matthias-g** [comment]
DKIM ist inzwischen auch eingerichtet und scheint zu funktionieren. Ich hoffe, dass das die Probleme reduziert.

Dieses Issue mache ich mal zu, da ich gerade keine weiteren Verbesserungsideen in der Richtung sehe.

**Comment by simonschaufi** [comment]
@matthias-g top, vielen Dank!

**Comment by mcnesium** [comment]
@matthias-g Wie hast du DKIM auf Uberspace 7 eingerichtet? [Die sagen selbst, dass das bei denen momentan nicht geht](https://uberspace.social/@ubernauten/105135306399562693)

**Comment by matthias-g** [comment]
> @matthias-g Wie hast du DKIM auf Uberspace 7 eingerichtet? [Die sagen selbst, dass das bei denen momentan nicht geht](https://uberspace.social/@ubernauten/105135306399562693)

Die verlinkte Aussage bezieht sich vermutlich auf das Einrichten von Signaturen für jede ausgehende E-Mail. Bei uns signiert die Rails Anwendung nur die aus der Anwendung verschickten E-Mails (mit [dkim](https://github.com/jhawthorn/dkim)).
